[project]
name = "Livt.Utils"
version = "1.0.0"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "Crc32Test"
]

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
